DROP DATABASE IF EXISTS schema;
CREATE DATABASE schema;
USE schema;

CREATE TABLE Users(
Id  INT PRIMARY KEY AUTO_INCREMENT,
lastname VARCHAR(32) DEFAULT NULL,
Password VARCHAR(16) DEFAULT NULL,
telephone INT
Email VARCHAR(32) DEFAULT NULL;
Date_Joined DATE
);

CREATE TABLE Jobs(
Id  INT PRIMARY KEY,
job_title VARCHAR(32) DEFAULT NULL,
JOB_DESCRIPTION VARCHAR(32) DEFAULT NULL,
CATEGORY VARCHAR(32) DEFAULT NULL,
COMPANY_name VARCHAR(32) DEFAULT NULL,
Company_location VARCHAR(32) DEFAULT NULL
date_posted DATE
)

CREATE TABLE Jobs Applied for(
Id  INT PRIMARY KEY DEFAULT NULL,
job_id  INT PRIMARY KEY,
user_id  INT PRIMARY KEY,
date_applied DATE
)